pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:victorvisionpd/serial-demo.git
          - cd serial-demo.git
          - git push --mirror git@github.com:victorvision/android-serial-demo.git
